version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: fz2024-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./conf/Dockerfile
    container_name: fz2024-php
    volumes:
      - ./www:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini  
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: fz2024-mail
    logging:
      driver: 'none'  
    ports:
      - 1025:1025 
      - 8025:8025